services:
  openvpn:
    image: agnusdei1207/offensive-security:latest
    container_name: openvpn-server
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    volumes:
      - openvpn_data:/etc/openvpn
    environment:
      - PUBLIC_IP=auto # Set to your public IP or leave as 'auto' to detect
      - OVPN_PORT=1194 # OpenVPN port
      - OVPN_PROTO=udp # OpenVPN protocol (udp or tcp)
      - OVPN_SERVER_NETWORK=10.8.0.0
      - OVPN_SERVER_NETMASK=255.255.255.0
    restart: unless-stopped

volumes:
  openvpn_data:
